### ISSUE TITLE
自动读取收费列表和收费历史记录实现原理？

### ISSUE THREAD

**Issue by tudousiji** [dxkite/NotificationDispatcher#1]
自动读取收费列表和收费历史记录实现原理，需要接入支付宝sdk吗？有没办法通过通知栏或者其他办法不接入支付宝sdk的情况下获取付款理由和订单号，

**Comment by dxkite** [comment]
可以，不接入SDK，不Root，通过Android的无障碍读取付款的信息，模拟用户操作手机，参考Android的 MonkeyRunner

**Comment by tudousiji** [comment]
> 可以，不接入SDK，不Root，通过Android的无障碍读取付款的信息，模拟用户操作手机，参考Android的 MonkeyRunner

那这样的话，用户手机上会出现自动打开支付宝，自动点击的情况，有没办法实现用户无感知读取

**Comment by dxkite** [comment]
这种不依赖SDK的话，实现就很麻烦了，支付宝和微信都不能双端登陆，要不就收款的时候放服务器上，要不就是从技术层面Hook（实现难度太高，没必要）。
再者，做无证收款的，也没有必要无感知，挺麻烦的，一般用也是技术人员用不，我反正现在收款就做一个简单的转发功能。。。

**Comment by tudousiji** [comment]
> 这种不依赖SDK的话，实现就很麻烦了，支付宝和微信都不能双端登陆，要不就收款的时候放服务器上，要不就是从技术层面Hook（实现难度太高，没必要）。
> 再者，做无证收款的，也没有必要无感知，挺麻烦的，一般用也是技术人员用不，我反正现在收款就做一个简单的转发功能。。。

但是我见过其他app，确实可以这样，不知道什么原理实现的，参考如下2个网址，如果你知道的话，麻烦分享下哈~~
https://blog.csdn.net/wx17749683191/article/details/81605099
http://shop.fteftk.com/paydemo/admin/order_public.php

**Comment by dxkite** [comment]
这个我之前看到过，实现方式是二维码的编码规则问题，主要的规则方式就是微信支付宝的二维码编码加密规则这个问题要解决，其他的话还好。

**Comment by dxkite** [comment]
另，这个应该不是无感知的收款

**Comment by tudousiji** [comment]
> 另，这个应该不是无感知的收款

下了他们的app，确实只需要通知权限就行，没有无障碍服务的权限

**Comment by dxkite** [comment]
可以把App给我一份么，我逆向分析一下

**Comment by tudousiji** [comment]
你留下联系方式 我发你，一起交流下

**Comment by dxkite** [comment]
项目commits有我邮箱

**Comment by tudousiji** [comment]
没找到唉。。。

**Comment by dxkite** [comment]
dxkite@163.com

**Comment by tudousiji** [comment]
发你了，反编译成功分享下哈，我这边反编译没成功，好像加固了

**Comment by dxkite** [comment]
看了下，主要的技术还是对微信和支付宝的二维码的编码解析，昨天反编译了微信的，基本上是Native的，最近没时间去分析算法，懒得做，不过你昨天发我的app已经逆向了，没有什么特殊的保护，基本上和我这个项目的实现方案一致，所以没有什么参考价值，主要还是二维码的生成方面需要逆向分析才行，不过我最近忙着写论文，没啥时间弄。
放一个图：
![image](https://user-images.githubusercontent.com/7450707/50261063-c5d78080-0445-11e9-9827-160cb5f9fd71.png)
核心代码如上，没啥特别的，参考我的代码就完事了。
